const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

async function inlineWorker() {
  const workerEntry = path.join(__dirname, '../src/workers/inference.worker.ts');
  const outputFile = path.join(__dirname, '../src/workers/worker-code.ts');

  console.log('📦 Compiling worker for inlining...');

  try {
    // 1. Bundle and minify the worker using esbuild
    const result = await esbuild.build({
      entryPoints: [workerEntry],
      bundle: true,
      minify: true,
      format: 'iife', // Standalone IIFE works best for Blobs
      platform: 'browser',
      write: false,   // Get content in memory
      sourcemap: false,
    });

    const code = result.outputFiles[0].text;

    // 2. Wrap in a TypeScript file that exports the code string
    // We use a template literal but escape backticks to avoid issues
    const tsWrapper = `/**
 * This file is AUTO-GENERATED by scripts/inline-worker.js
 * DO NOT EDIT MANUALLY.
 */
export const WORKER_CODE = ${JSON.stringify(code)};
`;

    fs.writeFileSync(outputFile, tsWrapper);
    console.log(`✅ Worker inlined successfully to: ${outputFile}`);
  } catch (err) {
    console.error('❌ Failed to inline worker:', err);
    process.exit(1);
  }
}

inlineWorker();
